### ISSUE TITLE
Why is power parameter for Renyi Efficency at default value 3.0 and not 2.5?

### ISSUE THREAD

**Issue by AnnaWegmann** [zouharvi/tokenization-scorer#6]
Maybe I missed sth, but I understood you found the power param 2.5 to be ideal in MT in your paper? Default var in your implementation seems to be 3.0 though.

**Comment by AnnaWegmann** [comment]
Well I guess this is a me problem. All examples are with 2.5.

**Comment by zouharvi** [comment]
The default is 3.0 for regularization purposes. We found 2.5 to be the best on a single language direction with a single MT model architecture with BLEU. Lots of ~bad~ decisions here.

![image](https://github.com/user-attachments/assets/f24d97e6-aa30-494a-9cf1-923acf576936)
