### ISSUE TITLE
Question about `get_prob_distribution()`

### ISSUE THREAD

**Issue by cosmaadrian** [zouharvi/tokenization-scorer#8]
Hello! Thank you for building this very useful resource!

To my understanding of the code and README, the function

```
def get_prob_distribution(text):
    words_freqs = Counter((w for l in text for w in l)).most_common()
    total_subwords = sum(x[1] for x in words_freqs)
    freqs = [
        freq
        for _, freq in words_freqs
    ]
    probs = [
        freq / total_subwords
        for freq in freqs
    ]
    vocab_size = len(words_freqs)
    return freqs, probs, vocab_size
```

should compute the distribution of tokens given a text.

However, if the input is a string, the lines
```
words_freqs = Counter((w for l in text for w in l)).most_common()
total_subwords = sum(x[1] for x in words_freqs)
```
compute counts __per character__. 

To my mind, the `words_freqs` variable should be 

```
words_freqs = Counter((w for w in text.split())).most_common()
```
with `text` being a "tokenized" string as you mention in the README.

Output for `get_prob_distribution_original("pick @@ed pick @@l @@ed pick @@les")`: 

```
([8, 6, 3, 3, 3, 3, 3, 2, 2, 1],
 [0.23529411764705882,
  0.17647058823529413,
  0.08823529411764706,
  0.08823529411764706,
  0.08823529411764706,
  0.08823529411764706,
  0.08823529411764706,
  0.058823529411764705,
  0.058823529411764705,
  0.029411764705882353],
 10)
```

Output for `get_prob_distribution_fixed("pick @@ed pick @@l @@ed pick @@les")`: 
```
([3, 2, 1, 1],
 [0.42857142857142855,
  0.2857142857142857,
  0.14285714285714285,
  0.14285714285714285],
 4)
```

Is this correct, or am I misunderstanding the code / input requirements?

**Comment by zouharvi** [comment]
There is a preprocessing step in the top-level [`score(..)`](https://github.com/zouharvi/tokenization-scorer/blob/17785b73d87cd74c701196c84229559073d343c6/tokenization_scorer/__init__.py#L6) function that normalizes the input (for which we decided to be reaally permissive, maybe a mistake).
Thus, all of the following pass:
```
import tokenization_scorer

assert tokenization_scorer.score("pick @@ed pick @@l @@ed pick @@les") == 0.8031528501359657
assert tokenization_scorer.score(["pick @@ed pick @@l @@ed pick @@les"]) == 0.8031528501359657
assert tokenization_scorer.score([["pick @@ed pick @@l @@ed pick @@les"]]) == 0.8031528501359657
assert tokenization_scorer.score("pick @@ed pick @@l @@ed pick @@les".split()) == 0.8031528501359657
```

The internal function works only with the normalized input and is not intended to be used outside of the package and is thus not accessible from top-level `tokenization_scorer` namespace.

Maybe I'm wrong though. I tend to make lots of bugs.

**Comment by cosmaadrian** [comment]
Ah right, I missed the code in the `__init__.py` file. I wanted to include only parts of this code to my own project, that's why I looked inside the package. Thanks for the response!
